<a href="https://colab.research.google.com/github/pranay-th/MNIST_Classification/blob/main/KNN_model4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [3]:
df_train=pd.read_csv("/content/mnist_train.csv")
df_test=pd.read_csv("/content/mnist_test.csv")

In [5]:
x= df_train.drop(columns=['5'], axis=1)

y= df_train['5']

In [6]:
scaler = StandardScaler()

scaler.fit(df_train)
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.30)


In [7]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [8]:
pred = knn.predict(X_test)

In [9]:
print(confusion_matrix(y_test,pred))

[[1726    0    2    0    0    1    4    0    3    0]
 [   0 2028    6    1    1    0    0    2    0    0]
 [  12   10 1712    5    2    1    1   23    6    2]
 [   1    2   11 1806    0   25    2    7   15    7]
 [   2    7    0    0 1693    0    3    3    0   38]
 [   3    2    1   18    2 1574   23    0    9   10]
 [   7    1    0    0    3    9 1764    0    2    0]
 [   0   14    6    2    3    0    0 1860    2   19]
 [   7   22    5   17    6   20   11    7 1610   17]
 [   3    0    0    9   22    6    4   21    2 1707]]


In [10]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1736
           1       0.97      1.00      0.98      2038
           2       0.98      0.97      0.97      1774
           3       0.97      0.96      0.97      1876
           4       0.98      0.97      0.97      1746
           5       0.96      0.96      0.96      1642
           6       0.97      0.99      0.98      1786
           7       0.97      0.98      0.97      1906
           8       0.98      0.93      0.96      1722
           9       0.95      0.96      0.96      1774

    accuracy                           0.97     18000
   macro avg       0.97      0.97      0.97     18000
weighted avg       0.97      0.97      0.97     18000

